---

- name: Molecule | Converge | Default scenario
  hosts: all

  vars_files:
    - "../vars/main.yml"

  environment:
    - PATH: "{{ homebrew_search_paths | join(':') }}"

  tasks:
    - name: Molecule | Converge | Include setup tasks
      ansible.builtin.include_tasks: "../tasks/setup.yml"
