---

- name: Molecule | Converge | Default scenario
  hosts: localhost

  vars_files:
    - "../vars/main.yml"

  tasks:
    - name: Molecule | Converge | Include setup tasks
      ansible.builtin.include_tasks: "../tasks/setup.yml"
