---

- name: Homebrew | Include | Install Homebrew on arm64 (M1) machines
  ansible.builtin.include_tasks: _partials/install-arm64.yml
  when: ansible_machine == 'arm64'
  tags:
    - brew-install

- name: Homebrew | Include | Install Homebrew on x86_64 (Intel) machines
  ansible.builtin.include_tasks: _partials/install-x86.yml
  when: ansible_machine == 'x86_64'
  tags:
    - brew-install

- name: Homebrew | Install | Ensure Homebrew directory exists
  ansible.builtin.file:
    path: "{{ brew_install_path }}"
    owner: "{{ brew_user }}"
    group: "{{ brew_group }}"
    state: directory
    mode: 0775
  become: true
  tags:
    - brew-install

- name: Homebrew | Install | Clone latest repository
  ansible.builtin.git:
    repo: "{{ brew.repository }}"
    version: "{{ brew.branch }}"
    dest: "{{ brew_install_path }}"
    update: false
    depth: 1
  become: true
  become_user: "{{ brew_user }}"
  tags:
    - brew-install

- name: Homebrew | Install | Ensure proper permissions and ownership on "{{ brew_bin_path }}" directory
  ansible.builtin.file:
    path: "{{ brew_bin_path }}"
    owner: "{{ brew_user }}"
    group: "{{ brew_group }}"
    state: directory
    mode: 0775
  become: true
  tags:
    - brew-install

- name: Homebrew | Install | Ensure proper ownership on "{{ brew_install_path }}" directory and it's contents
  ansible.builtin.file:
    path: "{{ brew_install_path }}"
    owner: "{{ brew_user }}"
    group: "{{ brew_group }}"
    state: directory
    recurse: true
  become: true
  tags:
    - brew-install

- name: Homebrew | Install | Check if binary is already in place
  ansible.builtin.stat:
    path: "{{ brew_bin_path }}/brew"
  register: brew_binary
  check_mode: false
  tags:
    - brew-install

- name: Homebrew | Install | Symlink brew to {{ brew_bin_path }}.
  ansible.builtin.file:
    src: "{{ brew_install_path }}/bin/brew"
    dest: "{{ brew_bin_path }}/brew"
    state: link
  when: not brew_binary.stat.exists
  become: true
  tags:
    - brew-install

- name: Homebrew | Install | Ensure proper folders are in place.
  ansible.builtin.file:
    path: "{{ brew_prefix }}/{{ item }}"
    owner: "{{ brew_user }}"
    group: "{{ brew_group }}"
    state: directory
    mode: 0775
  become: true
  loop: "{{ brew_folders }}"
  tags:
    - brew-install
