---

- name: Homebrew | Include | Install Homebrew on arm64 (M1) machines
  ansible.builtin.include_tasks: _partials/install-arm64.yml
  when: ansible_machine == 'arm64'
  tags:
    - brew-install

- name: Homebrew | Include | Install Homebrew on x86_64 (Intel) machines
  ansible.builtin.include_tasks: _partials/install-x86.yml
  when: ansible_machine == 'x86_64'
  tags:
    - brew-install

- name: Homebrew | Install | Ensure Homebrew directory exists
  ansible.builtin.file:
    path: "{{ homebrew_install_path }}"
    owner: "{{ brew_user }}"
    group: "{{ brew_group }}"
    state: directory
    mode: 0775
  become: true
  tags:
    - brew-install

- name: Homebrew | Install | Clone latest repository
  ansible.builtin.git:
    repo: "{{ homebrew_repository }}"
    version: "{{ homebrew_branch }}"
    dest: "{{ homebrew_install_path }}"
    update: false
    depth: 1
  become: true
  become_user: "{{ brew_user }}"
  tags:
    - brew-install

- name: Homebrew | Install | Ensure proper permissions and ownership on "{{ homebrew_bin_path }}" directory
  ansible.builtin.file:
    path: "{{ homebrew_bin_path }}"
    owner: "{{ brew_user }}"
    group: "{{ brew_group }}"
    state: directory
    mode: 0775
  become: true
  tags:
    - brew-install

- name: Homebrew | Install | Ensure proper ownership on "{{ homebrew_install_path }}" directory and it's contents
  ansible.builtin.file:
    path: "{{ homebrew_install_path }}"
    owner: "{{ brew_user }}"
    group: "{{ brew_group }}"
    state: directory
    recurse: true
  become: true
  tags:
    - brew-install

- name: Homebrew | Install | Check if binary is already in place
  ansible.builtin.stat:
    path: "{{ homebrew_bin_path }}/brew"
  register: brew_binary
  check_mode: false
  tags:
    - brew-install

- name: Homebrew | Install | Symlink brew to {{ homebrew_bin_path }}.
  ansible.builtin.file:
    src: "{{ homebrew_install_path }}/bin/brew"
    dest: "{{ homebrew_bin_path }}/brew"
    state: link
  when: not brew_binary.stat.exists
  become: true
  tags:
    - brew-install

- name: Homebrew | Install | Ensure proper folders are in place.
  ansible.builtin.file:
    path: "{{ homebrew_prefix }}/{{ folder_item }}"
    owner: "{{ brew_user }}"
    group: "{{ brew_group }}"
    state: directory
    mode: 0775
  become: true
  loop: "{{ homebrew_folders }}"
  loop_control:
    loop_var: folder_item
  tags:
    - brew-install

- name: Homebrew | Install | Register cache location
  ansible.builtin.command: "{{ homebrew_bin_path }}/brew --cache"
  register: brew_cache_path
  changed_when: false
  tags:
    - brew-install

- name: Homebrew | Install | Get installed version
  ansible.builtin.command: "{{ homebrew_bin_path }}/brew --version"
  register: brew_version
  changed_when: false
  tags:
    - brew-install

- name: Homebrew | Install | Get config
  ansible.builtin.command: "{{ homebrew_bin_path }}/brew --config"
  register: brew_config
  changed_when: false
  tags:
    - brew-install

- name: Homebrew | Install | Version debug
  ansible.builtin.debug:
    msg:
      - "{{ brew_version }}"
      - "{{ brew_config }}"
  tags:
    - brew-install
