---

- name: Homebrew | Set ownership variables
  ansible.builtin.set_fact:
    brew_user: "{{ brew_user | default(ansible_user_id) }}"
    brew_group: "{{ brew_group | default(ansible_user_gid) }}"

- name: Homebrew | Include | Install homebrew itself on system
  ansible.builtin.include_tasks: install.yml
  tags:
    - brew-install

- name: Homebrew | Include | Tap custom repositories
  ansible.builtin.include_tasks: _partials/tap.yml
  loop: "{{ brew.taps }}"
  when: brew.taps | length > 0
  tags:
    - brew-tap

- name: Homebrew | Include | Install packages
  ansible.builtin.include_tasks: _partials/package.yml
  loop: "{{ brew.packages }}"
  when: brew.packages | length > 0
  tags:
    - brew-install-packages

- name: Homebrew | Include | Install casks
  ansible.builtin.include_tasks: _partials/cask.yml
  loop: "{{ brew.casks }}"
  when: brew.casks | length > 0
  tags:
    - brew-install-casks
