---

- name: Homebrew | Include | Get facts
  ansible.builtin.include_tasks: pre-facts.yml
  tags:
    - brew-install
    - brew-analytics
    - brew-update
    - brew-taps
    - brew-packages
    - brew-casks

- name: Homebrew | Include | Install homebrew itself on system
  ansible.builtin.include_tasks: install.yml
  tags:
    - brew-install
    - brew-analytics
    - brew-update
    - brew-taps
    - brew-packages
    - brew-casks

- name: Homebrew | Include | Configure analytics
  ansible.builtin.include_tasks: _partials/analytics.yml
  tags:
    - brew-analytics

- name: Homebrew | Include | Update homebrew packages
  ansible.builtin.include_tasks: update.yml
  tags:
    - brew-update

- name: Homebrew | Include | Tap custom repositories
  ansible.builtin.include_tasks: _partials/tap.yml
  tags:
    - brew-taps

- name: Homebrew | Include | Install packages
  ansible.builtin.include_tasks: _partials/package.yml
  tags:
    - brew-packages

- name: Homebrew | Include | Install casks
  ansible.builtin.include_tasks: _partials/cask.yml
  when: ansible_os_family == 'Darwin'
  tags:
    - brew-casks

...
