---

- name: Homebrew | Set ownership variables
  ansible.builtin.set_fact:
    brew_user: "{{ homebrew_user | default(ansible_user_id) }}"
    brew_group: "{{ homebrew_group | default(ansible_user_gid) }}"
  tags:
    - brew-install
    - brew-analytics
    - brew-taps
    - brew-packages
    - brew-casks
    - brew-update
