---

- name: Homebrew | Update block
  block:
    - name: Homebrew | Update | Register cache location
      ansible.builtin.command: "{{ brew_bin_path }}/brew --cache"
      register: brew_cache_path
      changed_when: false
      check_mode: false
      tags:
        - brew-update

    - name: Homebrew | Update | Force update brew after installation.
      ansible.builtin.command: "{{ brew_bin_path }}/brew update --force"
      when: not brew_binary.stat.exists
      tags:
        - brew-update
  become: "{{ (brew_user != ansible_user_id) | bool }}"
  become_user: "{{ brew_user }}"
