---

- name: Homebrew | Removing casks
  community.general.homebrew_cask:
    name: "{{ item }}"
    state: absent
  loop: "{{ brew.casks_remove }}"
  when: brew.casks_remove | lenght > 0

- name: Homebrew | Installing casks
  community.general.homebrew_cask:
    name: "{{ brew.casks }}"
    state: present
    # Upgrades Disabled Here Due to: https://github.com/ansible-collections/community.general/issues/1647
    # update_homebrew: true
    accept_external_apps: true
    sudo_password: "{{ brew_sudo_password }}"
  retries: "{{ brew.retries }}"
  delay: "{{ brew.delay }}"
  register: install_cask
  until: install_cask is not failed
  become: "{{ (brew_user != ansible_user_id) | bool }}"
  become_user: "{{ brew_user }}"
  when: brew.casks | length > 0
  tags:
    - brew-casks
  notify:
    - brew-clear-cache
