---

- name: Homebrew | Installing, updating and deleting casks
  community.general.homebrew_cask:
    name: "{{ item.name | default(item) }}"
    state: "{{ item.state | default(brew_cask_install_state) }}"
    options: "{{ item.options | default('appdir=' + brew.cask_appdir) }}"
    greedy: "{{ brew.cask_greedy_mode }}"
    # Upgrades Disabled Here Due to: https://github.com/ansible-collections/community.general/issues/1647
    # update_homebrew: true
    accept_external_apps: true
    sudo_password: "{{ brew_sudo_password }}"
  retries: "{{ brew.retries }}"
  delay: "{{ brew.delay }}"
  register: install_cask
  until: install_cask is not failed
  become: "{{ (brew_user != ansible_user_id) | bool }}"
  become_user: "{{ brew_user }}"
  when: brew.casks | length > 0
  loop: "{{ brew.casks }}"
  tags:
    - brew-casks
  notify:
    - brew-clear-cache
