---

- name: Homebrew | Install | Add bin dir to system-wide $PATH on RedHat family Linux
  ansible.builtin.copy:
    content: 'export PATH=$PATH:{{ homebrew_bin_path }}'
    dest: /etc/profile.d/brew.sh
  when:
    - ansible_env.PATH is not search(homebrew_bin_path)
    - ansible_os_family == 'RedHat' or ansible_os_family == 'Rocky'
  tags:
    - brew-install

- name: Homebrew | Install | Add bin dir to system-wide $PATH on Debian family Linux
  ansible.builtin.lineinfile:
    dest: /etc/environment
    state: present
    backrefs: true
    regexp: PATH=(["]*)((?!.*?{{ homebrew_bin_path }}).*?)(["]*)$
    line: PATH=\1\2:{{ homebrew_bin_path }}\3
  when:
    - ansible_os_family == 'Debian'
  tags:
    - brew-install

- name: Homebrew | Install | Check if brew.sh $PATH file exists on macOS
  ansible.builtin.stat:
    path: /etc/paths.d/brew.sh
  register: brewsh_file
  when:
    - ansible_os_family == 'Darwin'
  tags:
    - brew-install

- name: Homebrew | Install | Add bin dir to system-wide $PATH on macOS
  ansible.builtin.copy:
    content: 'export PATH=$PATH:{{ homebrew_bin_path }}'
    # https://stackoverflow.com/questions/22465332/setting-path-environment-variable-in-osx-permanently/51218283#51218283
    dest: /etc/paths.d/brew.sh
  when:
    - ansible_os_family == 'Darwin' and not brewsh_file.stat.exists
  become: true
  tags:
    - brew-install

...
