---

- name: Homebrew | Ensure parent directory has correct permissions (Intel)
  ansible.builtin.file:
    path: "{{ brew_prefix }}"
    owner: root
    group: wheel
    state: directory
    mode: 0755
  become: true
