---

- name: Homebrew | Ensure parent directory has correct permissions (M1)
  ansible.builtin.file:
    path: "{{ homebrew_prefix }}"
    owner: "{{ brew_user }}"
    state: directory
    mode: 0755
  become: true
