---

- name: Homebrew | Ensure parent directory has correct permissions on Intel macOS
  ansible.builtin.file:
    path: "{{ homebrew_prefix }}"
    owner: root
    group: wheel
    state: directory
    mode: 0755
  become: true
  when: ansible_os_family == 'Darwin'
  tags:
    - brew-install

...
