---

- name: Homebrew | Installing packages"
  community.general.homebrew:
    name: "{{ brew.packages }}"
    state: "{{ brew_install_state }}"
    update_homebrew: true
  retries: "{{ brew.retries }}"
  delay: "{{ brew.delay }}"
  register: install_package
  until: install_package is not failed
  become: true
  become_user: "{{ brew_user }}"
  when: brew.packages | length > 0
  tags:
    - brew-install-packages
  notify:
    - brew-clear-cache
