---

- name: Homebrew | Installing, updating and deleting packages
  community.general.homebrew:
    name: "{{ item.name | default(item) }}"
    state: "{{ item.state | default(brew_install_state) }}"
    update_homebrew: "{{ brew.accept_external_casks }}"  # Update is handled by separate task, do we need to disable this?
  retries: "{{ brew.retries }}"
  delay: "{{ brew.delay }}"
  register: install_package
  until: install_package is not failed
  become: "{{ (brew_user != ansible_user_id) | bool }}"
  become_user: "{{ brew_user }}"
  when: brew.packages | length > 0
  loop: "{{ brew.packages }}"
  tags:
    - brew-packages
  notify:
    - brew-clear-cache
