---

- name: Homebrew | Tapping Homebrew repositories
  community.general.homebrew_tap:
    name: "{{ item.name | default(item) }}"
    state: "{{ item.state | default('present') }}"
    url: "{{ item.url | default(omit) }}"
  retries: "{{ brew.retries }}"
  delay: "{{ brew.delay }}"
  register: install_tap
  until: install_tap is not failed
  become: "{{ (brew_user != ansible_user_id) | bool }}"
  become_user: "{{ brew_user }}"
  when: brew.taps | length > 0
  loop: "{{ brew.taps }}"
  tags:
    - brew-taps
