---

- name: Homebrew | Tapping Homebrew repository - "{{ item }}"
  community.general.homebrew_tap:
    name: "{{ brew.taps }}"
  retries: "{{ brew.retries }}"
  delay: "{{ brew.delay }}"
  register: install_tap
  until: install_tap is not failed
  become: true
  become_user: "{{ brew_user }}"
  when: brew.taps | length > 0
  tags:
    - brew-tap
