---

- name: Brew-clear-cache
  ansible.builtin.file:
    path: "{{ brew_cache_path.stdout | trim }}"
    state: absent
  when: homebrew_clear_cache | bool
  become: "{{ (brew_user != ansible_user_id) | bool }}"
  become_user: "{{ brew_user }}"

...
