---

- name: Converge
  hosts: all

  vars:
    homebrew_user: linuxbrew
    homebrew_group: linuxbrew

  tasks:
    - name: Include elliotweiser.osx-command-line-tools
      ansible.builtin.include_role:
        name: elliotweiser.osx-command-line-tools
      when: ansible_os_family == 'Darwin'

    - name: Include elliotweiser.osx-command-line-tools
      ansible.builtin.include_role:
        name: geerlingguy.git
      when: ansible_system == 'Linux'

    - name: Include ansible-role-homebrew
      ansible.builtin.include_role:
        name: ansible-role-homebrew
