---

dependency:
  name: galaxy
driver:
  name: docker

platforms:
  - name: debian-based-instance
    image: geerlingguy/docker-ubuntu2204-ansible:latest
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
    pre_build_image: true
    privileged: true

provisioner:
  name: ansible

verifier:
  name: ansible

# Linting handled by Makefile and separate CI tasks
# lint: |
#   set -e
#   yamllint .
#   ansible-lint .
