---

- name: Verify
  hosts: all
  gather_facts: false
  tasks:
  - name: Install Formulae
    community.general.homebrew:
      path: "{{ homebrew_search_paths | join(':') }}"
      name: run
      state: present
