---

- name: Verify
  hosts: all
  become: true

  vars:
    homebrew_user: linuxbrew
    homebrew_search_paths:
      - /usr/local/bin
      - /opt/homebrew/bin
      - /home/linuxbrew/.linuxbrew/bin

  tasks:
    - name: Install Formulae
      community.general.homebrew:
        path: "{{ homebrew_search_paths | join(':') }}"
        name: run
        state: present
      become: "{{ (homebrew_user != ansible_user_id) | bool }}"
      become_user: "{{ homebrew_user }}"
