---

dependency:
  name: galaxy
  options:
    role-file: requirements.yml
    requirements-file: requirements.yml

# Run locally
driver:
  name: delegated
  options:
    managed: false
    ansible_connection_options:
      ansible_connection: local
      ansible_sudo_pass: "${ANSIBLE_SUDO_PASSWORD}"

platforms:
  - name: Local-Connection

provisioner:
  name: ansible
  inventory:
    group_vars:
      all:
        ansible_become_password: "${ANSIBLE_SUDO_PASSWORD}"
        ansible_user: "${USER}"
  playbooks:
    converge: "../_partials/playbooks/converge-local.yml"
    verify: "../_partials/playbooks/verify.yml"

verifier:
  name: ansible
